# Generated by Django 3.1 on 2021-07-08 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(default=uuid.UUID('536be602-0e8c-4723-b424-0023010c638c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
